repos:

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: 'v0.2.2' # Ruff version.
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]

- repo: https://github.com/psf/black
  rev: 24.2.0
  hooks:
  - id: black
    args: [--safe]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-docstring-first
  - id: check-merge-conflict
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
    exclude: ^deployment/helm
  - id: check-toml
  - id: check-json
  - id: check-added-large-files
    language_version: python3
