repos:

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.1.4' # Ruff version.
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]

- repo: https://github.com/psf/black
  rev: 23.10.1
  hooks:
  - id: black
    args: [--safe]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-docstring-first
  - id: check-merge-conflict
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
    exclude: ^deployment/helm
  - id: check-toml
  - id: check-json
  - id: check-added-large-files
    language_version: python3

- repo: local
  hooks:
    - id: pyre-check
      name: pyre-check
      stages: [commit]
      language: python
      entry: pdm run pyre check
      types: [python]
      pass_filenames: false
      additional_dependencies: []
